cmake_minimum_required(VERSION 3.25.0)
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/VERSION" VERSION_CONTENT)
string(STRIP "${VERSION_CONTENT}" PROJECT_VERSION_RAW)
if (NOT PROJECT_VERSION_RAW MATCHES "^[0-9]+\\.[0-9]+$")
    message(FATAL_ERROR "Invalid version format in VERSION file: '${PROJECT_VERSION_RAW}'")
endif () 
project(dsp_seed_search VERSION ${PROJECT_VERSION_RAW} LANGUAGES CXX C)
message(STATUS "project version: ${PROJECT_VERSION_RAW}")

set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /MANIFEST:NO")
set(CMAKE_CXX_STANDARD 17) set(CMAKE_INTERPROCEDURAL_OPTIMIZATION OFF)
option(BUILD_PYTHON "build python file" ON)

message(STATUS "CMAKE_C_COMPILER = ${CMAKE_C_COMPILER}")
message(STATUS "CMAKE_CXX_COMPILER = ${CMAKE_CXX_COMPILER}")
message(STATUS "CMAKE_BUILD_TYPE = ${CMAKE_BUILD_TYPE}")
message(STATUS "CMAKE_INSTALL_PREFIX = ${CMAKE_INSTALL_PREFIX}")
message(STATUS "BUILD_PYTHON = ${BUILD_PYTHON}")

add_compile_options(/GS)
add_compile_options(/utf-8)
if (${CMAKE_BUILD_TYPE} MATCHES "Release")
    add_compile_options(/O2)
    add_link_options(/OPT:REF /OPT:ICF)
else ()
    add_compile_options(/Zi /Od)
endif ()

set(PROJECT_BUILD_PATH ${PROJECT_BINARY_DIR})
set(PROJECT_3RDPARTY_SRC_DIR ${PROJECT_SOURCE_DIR}/3rdparty)
set(PROJECT_3RDPARTY_BIN_DIR ${PROJECT_SOURCE_DIR}/output/3rdparty)

if (BUILD_PYTHON STREQUAL "ON")
    # 获取Python头文件路径
    find_program(PYTHON_EXECUTABLE NAMES python3 python)
    if (NOT PYTHON_EXECUTABLE)
        message(FATAL_ERROR "Python not found")
    endif ()
    execute_process( COMMAND ${PYTHON_EXECUTABLE} -c "import sysconfig; print(sysconfig.get_path('include'))" OUTPUT_VARIABLE PYTHON_INCLUDE_DIR OUTPUT_STRIP_TRAILING_WHITESPACE )
    execute_process( COMMAND ${PYTHON_EXECUTABLE} -c "import sys; import os; import pybind11; print(os.path.dirname(pybind11.__file__))" OUTPUT_VARIABLE PYTHON_PYBIND11_HOME OUTPUT_STRIP_TRAILING_WHITESPACE )
    set(pybind11_cmake_dir "${PYTHON_PYBIND11_HOME}/share/cmake/pybind11")
    # 检查路径是否存在且是目录
    if (NOT EXISTS "${pybind11_cmake_dir}" OR NOT IS_DIRECTORY "${pybind11_cmake_dir}")
        message(SEND_ERROR "Can not find pybind11 directory: ${pybind11_cmake_dir}\nPlease 'pip3 install pybind11 or pybind11-dev'")
    else()
        message(STATUS "Find pybind11 at: ${pybind11_cmake_dir}")
    endif ()
endif ()

add_subdirectory(3rdparty) 
add_subdirectory(cpp_source_code)